version: "3"
services:
  pern-products:
    container_name: pern-database
    image: postgres:16.2
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pern-products
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data